import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/ui/nav-bar";
import { UserProvider } from "../providers/user-provider";
import {
  agathoRegular,
  agathoLight,
  agathoMedium,
  agathoBold,
  agathoNarrow,
  agathoRegularCaps,
  agathoBoldCaps,
  agathoLightCaps,
} from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${agathoRegular.variable} 
        ${agathoLight.variable} 
        ${agathoMedium.variable} 
        ${agathoBold.variable}
        ${agathoNarrow.variable}
        ${agathoRegularCaps.variable}
        ${agathoBoldCaps.variable}
        ${agathoLightCaps.variable}
      `}
    >
      <body className="font-sans antialiased">
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
